### ISSUE TITLE
Investigar como ingresar con API de facebook y google

### ISSUE THREAD

**Issue by midestefanis** [SantaPesca/ui-web#10]
Para facebook cree una cuenta como desarrollador:
https://developers.facebook.com/apps/2901054713294810/dashboard/

Luego tuve que crear una politica de seguridad, lo hice a través de acá:
https://app-privacy-policy-generator.firebaseapp.com/#

Luego terminó acá:
https://app.flycricket.com/app/aed44800eed24bbdb848bbdaec8de53a?created=1&privacy=1

**Comment by midestefanis** [comment]
En ambas API me pide una URL, supongo q es la de redirección. No sé cual es el endpoint de "home" @GastonZianni . Pero deberia ser localhost/algo no?

![image](https://user-images.githubusercontent.com/59846928/78377422-f80ee200-75a5-11ea-8612-544ca06f792d.png)
![image](https://user-images.githubusercontent.com/59846928/78377464-06f59480-75a6-11ea-93a1-1ce8bb8ad1e3.png)

P.D: Facebook es re hincha pija, te pide de todo

**Comment by GastonZianni** [comment]
Trabajando en esto
